---
- name: Enable OSPF
  nclu:
    commands:
    - add ospf router-id {{ routerid[inventory_hostname].rid }}
    - add ospf network {{item.prefix}} area {{item.area}}
  loop:
    - { prefix: 192.168.0.0/16,area: 0.0.0.0}
    